import { Component, TemplateRef, ViewChild, OnInit, AfterViewInit, ChangeDetectorRef } from '@angular/core';
import { FormBuilder, FormGroup, Validators, FormArray, FormControl } from '@angular/forms';
import { AuthService } from '../../../../../auth/auth.service';

import { LeaderService } from '../../dash-services/leader.service';
import { LeaderResponse } from '../../dash-services/leader.service';
import { Observable } from 'rxjs';

export interface Leader {
  id?: number; // Optional since it will be auto-generated by the backend
  name: string | null;
  gift: string | null;
  info: string | null;
  imagePath: string | null;
  socialMediaProfiles: SocialMedia[];
}


interface SocialMedia {
  platformName: string;
  platformUrl: string;
}

@Component({
  selector: 'app-dash-leaders',
  templateUrl: './dash-leaders.component.html',
  styleUrls: ['./dash-leaders.component.css']
})
export class DashLeadersComponent implements OnInit, AfterViewInit {
  // Tab data
  tabItems = [
    { id: 0, label: 'View Leaders' },
    { id: 1, label: 'Create New Leader' }
  ];
  tabContentTemplates: TemplateRef<any>[] = [];

  activeTabIndex: number = 0;

  @ViewChild('firstTabContent') firstTabContent!: TemplateRef<any>;
  @ViewChild('secondTabContent') secondTabContent!: TemplateRef<any>;

  // Form and data
  leaderForm!: FormGroup;
  socialMedia: FormArray;
  leaders: Leader[] = [];
  //leaders: Observable<Leader[]> | undefined; 
  selectedFileName: string | null = null;
  imagePath = new FormControl('');
  leadersCount: number = 0;
  // pagination
  pageSize: number = 5;
  currentPage: number = 1;
  totalPages: number = 0;


  platformKeys: string[] = ['Facebook', 'Youtube', 'Instagram', 'TikTok', 'Whatsapp'];
  apiUrl: string;

  isEditing: boolean = false;
  leaderToUpdate: Leader | null = null;
  isCreating: boolean = true; // Initially set to true
  
  constructor(
    private leaderService: LeaderService, 
    private fb: FormBuilder,
    private cdr: ChangeDetectorRef,
    
    
  ) {
    this.apiUrl = leaderService.ApiUrl;
    this.socialMedia = this.fb.array([this.createSocialMediaGroup()]);
  }
  

  ngOnInit() {
    this.initializeForm();
    this.loadLeaders();
  }

  ngAfterViewInit(): void {
    this.tabContentTemplates = [this.firstTabContent, this.secondTabContent];
    this.cdr.detectChanges(); // Avoid ExpressionChangedAfterItHasBeenCheckedError
  }

  // Initialize the form
  private initializeForm(): void {
    this.leaderForm = this.fb.group({
      name: ['', Validators.required],
      gift: ['', Validators.required],
      info: ['', Validators.required],
      imagePath: [''],
      socialMedia: this.fb.array([])
     // socialMedia: this.fb.array([this.createSocialMediaGroup()]), // Start with one social media entry
    });
  }

  // Create a social media form group
  createSocialMediaGroup(): FormGroup {
  return this.fb.group({
      platformName: ['', Validators.required],
      platformUrl: ['', [Validators.required, Validators.pattern(/https?:\/\/.*/)]],
    });
  }

  // Get the social media controls as a FormArray
  get socialMediaControls(): FormArray {
    return this.leaderForm.get('socialMedia') as FormArray;
  }


  // Load leaders from the server
  loadLeaders(): void {
    this.leaderService.getLeaders(this.currentPage, this.pageSize).subscribe( // Pass parameters
      (response: LeaderResponse) => {
        this.leaders = response.leaders;
        this.leadersCount = response.totalCount;
        this.calculateTotalPages(); // Calculate total pages
        console.log("Leaders data:", this.leaders);
      },
      (error) => {
        console.error('Error loading leaders:', error);
      }
    );
  }
  
  // Add a new social media form group
  addSocialMedia(): void {
    this.socialMediaControls.push(this.createSocialMediaGroup());
  }

  // Remove a specific social media form group
  removeSocialMedia(index: number): void {
    this.socialMediaControls.removeAt(index);
  }
   

  onCreateLeader(): void {
    if (this.leaderForm.valid && this.isCreating) { // Only create if isCreating is true
        const leaderData = { ...this.leaderForm.value };
        this.leaderService.createLeader(leaderData).subscribe({
            next: (createdLeader) => {
                console.log("Leader created successfully:", createdLeader);
                if (createdLeader?.id) {
                    this.handleImageUpload(createdLeader, () => {
                        this.loadLeaders();
                        this.resetForm();
                        this.activeTabIndex = 0;
                    });
                } else {
                    console.error("Created leader or ID is undefined.");
                    this.loadLeaders();
                    this.resetForm();
                    this.activeTabIndex = 0;
                }
            },
            error: (error) => {
                console.error("Error creating leader:", error);
            }
        });
    }
  }

  onUpdateLeader(): void {
    if (this.leaderForm.valid && this.leaderToUpdate?.id) {
      const formData = new FormData();
      formData.append('id', this.leaderToUpdate.id.toString());
      formData.append('name', this.leaderForm.get('name')?.value);
      formData.append('gift', this.leaderForm.get('gift')?.value);
      formData.append('info', this.leaderForm.get('info')?.value);
  
      if (this.selectedFile) {
        formData.append('image', this.selectedFile, this.selectedFile.name);
      }
  
      // Serialize social media properly
      const socialMediaProfiles = this.leaderForm.get('socialMedia') as FormArray;
      formData.append('socialMediaProfiles', JSON.stringify(socialMediaProfiles.value));
  
      this.leaderService.updateLeader(this.leaderToUpdate.id, formData).subscribe({
        next: () => {
          console.log('Leader updated successfully');
          this.isEditing = false;
          this.leaderToUpdate = null;
          this.resetForm();
          this.activeTabIndex = 0;
          this.loadLeaders();
        },
        error: (error) => console.error('Error updating leader', error)
      });
    }
  }
  

  cancelUpdate(): void {
    this.isEditing = false;
    this.leaderToUpdate = null;
    this.leaderForm.reset(); // Clear the form
    this.activeTabIndex = 0; // Return to the "View Leaders" tab (if applicable)
    this.loadLeaders(); // Refresh the list of leaders
  }

  
  onFileSelected(event: any): void {
    this.selectedFile = event.target.files[0] || null;
    this.selectedFileName = this.selectedFile ? this.selectedFile.name : null;
  }

  private selectedFile: File | null = null; // Add this line to your code
  
  startEdit(leader: Leader | null | undefined): void {
    if (!leader) {
      console.error("Leader is null or undefined. Cannot start edit.");
      return;
    }
  
    this.isEditing = true;
    this.isCreating = false;
    this.leaderToUpdate = leader;
  
    this.leaderForm.patchValue({
      name: leader.name,
      gift: leader.gift,
      info: leader.info,
      imagePath: leader.imagePath
    });
  
    this.socialMediaControls.clear();
    leader.socialMediaProfiles.forEach(profile => {
      this.socialMediaControls.push(this.fb.group({
        platformName: [profile.platformName, Validators.required],
        platformUrl: [profile.platformUrl, [Validators.required, Validators.pattern(/https?:\/\/.*/)]]
      }));
    });
  
    this.activeTabIndex = 1;
  }
  


  private handleImageUpload(leader: any, callback: () => void) {
      if (this.selectedFile) {
          if (leader && leader.id) { // Make sure leader and id are available
              this.leaderService.uploadImage(this.selectedFile, leader.id).subscribe({
                  next: (imageResponse: any) => {
                      console.log("Image uploaded:", imageResponse);
                      callback();
                  },
                  error: (imageError: any) => {
                      console.error('Error uploading file:', imageError);
                      callback();
                  }
              });
          } else {
              console.error("Leader or ID is undefined. Cannot upload image.");
              callback(); // Still call the callback to proceed
          }
      } else {
          callback();
      }
  }

  // After Creating the leader we reset the form for new entry
  resetForm(): void {
    this.leaderForm.reset(); // Reset all form values
    this.socialMediaControls.clear(); // Clear social media fields
    this.selectedFileName = null; // Reset selected file name to null
    this.selectedFile = null; // Clear file reference
    this.initializeForm(); // Reinitialize the form structure
  } 

  getImageUrl(imagePath: string): string {
    return `${this.leaderService.ApiUrl}/${imagePath}`;
  }

  onDeleteLeader(leader: Leader): void {
    if (!leader.id) { // Check for 'id'
        console.error("leader.id is undefined");
        return;
    }

    if (confirm("Are you sure you want to delete this leader?")) {
        this.leaderService.deleteLeader(leader.id).subscribe({ // Use leader.id
            next: () => {
                console.log("Leader deleted successfully");
                this.loadLeaders();
            },
            error: (error) => {
                console.error("Error deleting leader:", error);
            }
        });
    }
  }


  onTabSelected(tabId: number): void {
    this.activeTabIndex = tabId;
    
    if (tabId === 1 && !this.isEditing) { // Only reset if NOT editing
      this.resetForm();
      this.isCreating = true;
      this.leaderToUpdate = null;
    }
  }

  goToPreviousPage() {
    if (this.currentPage > 1) {
        this.currentPage--;
        this.loadLeaders();
    }
}

  goToNextPage() {
      if (this.currentPage < this.totalPages) {
          this.currentPage++;
          this.loadLeaders();
      }
  }

  calculateTotalPages() {
    this.totalPages = Math.ceil(this.leadersCount / this.pageSize);
  }

  
}  
